[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pydocmaker"
dynamic = ["version", "dependencies"]
description = "A minimal python document maker to create and show reports (including figures and tables) from within python and export them to markdown, pdf, html, and word."
readme = { file="README.md", content-type="text/markdown" }
license = "MIT"

authors = [
    { name="Tobias Glaubach" }
]

classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only"
]
requires-python = ">=3.8"


[project.urls]
Homepage = "https://pydocmaker.readthedocs.io"
Repository = "https://github.com/TobiasGlaubach/pydocmaker"
"Bug Tracker" = "https://github.com/TobiasGlaubach/pydocmaker/issues"
Documentation = "https://pydocmaker.readthedocs.io"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pydocmaker*"]

[tool.setuptools.package-data]
"pydocmaker" = ["templates/**"]

[tool.setuptools.dynamic]
version = {attr = "pydocmaker.__version__"}
dependencies = {file = ["requirements.txt"]}